apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order-investment-created-subscription
spec:
  pubsubname: investments-orders
  topic: "order-investment-created"
  route: "/order-investment-created"